version: '3'

secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  DB_ROOT_PWD:
    file: /root/.secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: /root/.secrets/mysql_pwd.txt

services:
    freshrss:
        image: freshrss/freshrss:edge
        container_name: freshrss
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
        volumes:
        # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
        - /portainer/AppData/freshrss/data:/var/www/FreshRSS/data
        # Optional volume for storing third-party extensions
        - /portainer/AppData/freshrss/extensions:/var/www/FreshRSS/extensions
        ports:
        # If you want to open a port 8080 on the local machine:
        - "8780:80"
        environment:
        # A timezone America/Chicago (default is UTC)
            TZ: America/Chicago
        # Cron job to refresh feeds at specified minutes
            CRON_MIN: '2,32'
        # 'development' for additional logs; default is 'production'
            FRESHRSS_ENV: production
            FRESHRSS_INSTALL: |-
                --api_enabled
                --base_url ${BASE_URL}
                --db-base ${DB_BASE}
                --db-host ${DB_HOST}
                --db-password /run/secrets/MYSQL_PWD
                --db-type mysql
                --db-user ${DB_USER}
                --default_user mukesh
                --language en
            FRESHRSS_USER: |-
                --api_password ${ADMIN_API_PASSWORD}
                --email ${ADMIN_EMAIL}
                --language en
                --password ${ADMIN_PASSWORD}
                --user mukesh
        depends_on:
            - db
    db:
        image: mariadb
        container_name: freshrss-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
        volumes:
            - /portainer/AppData/freshrss/db:/var/lib/mysql
        secrets:
            - DB_ROOT_PWD
            - MYSQL_PWD
networks:
  default:
      external: true
      name: mukeshio-network